disabled_rules: # rules identifiers to exclude from running
  - colon
  - line_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

line_length: 200
type_body_length:
  - 300 # warning
  - 400 # error
